app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['as' => 'auth.'], function(){
    // Authentication routes...
    Route::get('connexion', 'Auth\AuthController@getLogin')->name('login');
    Route::post('connexion', 'Auth\AuthController@postLogin')->name('login');
    Route::get('deconnexion', 'Auth\AuthController@getLogout')->name('logout');

    // Registration routes...
    Route::get('inscription', 'Auth\AuthController@getRegister')->name('register');
    Route::post('inscription', 'Auth\AuthController@postRegister')->name('register');
});


// Routes inaccessibles si l'utilisateur n'est pas authentifié
Route::group(['middleware' => 'auth'], function(){
            Route::get('/', 'PageController@newsFeed')->name('news-feed');
            Route::get('/annuaire', 'UserController@index')->name('directory');
            Route::resource('users', 'UserController');
            Route::post('/users/{users}/friends', 'UserController@storeFriend')->name('users.friends.store');
            Route::resource('messages', 'MessageController', ['only' => ['store', 'destroy']]);
            Route::post('messages/{messages}/like', 'MessageController@like')->name('messages.likes.store');
            Route::resource('messages.comments', 'CommentController', ['only' => ['store', 'destroy']]);
            Route::post('messages/{messages}/comments/{comments}/like', 'CommentController@like')->name('messages.comments.likes.store');
});

resources/views/layout/facebook.blade.php
	<!DOCTYPE html>
	<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Facebook</title>

		<link href="{{ asset('/css/bootstrap.css') }}" rel="stylesheet">
		<link href="{{ asset('/css/facebook.css') }}" rel="stylesheet">

		<!-- Fonts -->
		<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="wrapper">
			<div class="box">
				<div class="row row-offcanvas row-offcanvas-left">
					<div class="column col-sm-12 col-xs-12" id="main">
						<div class="navbar navbar-blue navbar-static-top">
							<div class="navbar-header">
								<a href="" class="navbar-brand logo">b</a>
							</div>

							<nav class="collapse navbar-collapse" role="navigation">
								<ul class="nav navbar-nav">
									<li>
										<a href="{{ route('news-feed') }}"><i class="glyphicon glyphicon-home"></i> Accueil</a>
									</li>
									<li>
										<a href="{{ route('users.show', ['users' => Auth()->user()->id]) }}" role="button" data-toggle="modal"><i class="glyphicon glyphicon-user"></i> {{ auth()->user()->name }}</a>
									</li>
									<li>
										<a href="{{ route('users.edit', ['users' => Auth()->user()->id]) }}" role="button" data-toggle="modal"><i class="glyphicon glyphicon-edit"></i> Editer</a>
									</li>
									 <li>
										<a href="{{ route('directory') }}" role="button" data-toggle="modal"><i class="glyphicon glyphicon-th"></i> Trouver des amis</a>
									</li>
								</ul>
								<ul class="nav navbar-nav navbar-right">
									<li>
										<a href="{{ route('auth.logout') }}" role="button" data-toggle="modal"><i class="glyphicon glyphicon-log-out"></i> Déconnexion</a>
									</li>
								</ul>
							</nav>
						</div>
						<div class="padding">
							<div class="col-sm-6 col-sm-offset-3">
								<div class="padding">
									<div class="full col-sm-9">
											@yield('content')
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>



		<!-- Scripts -->
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
	</body>
	</html>

resources/views/layout/visitor.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Facebook</title>

	<link href="{{ asset('/css/bootstrap.css') }}" rel="stylesheet">
	<link href="{{ asset('/css/facebook.css') }}" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<div class="wrapper">
		<div class="box">
			<div class="row row-offcanvas row-offcanvas-left">
				<div class="column col-sm-12 col-xs-12" id="main-blue">
					<div class="navbar navbar-blue navbar-static-top">  
						<div class="navbar-header">
						</div>

						<nav class="collapse navbar-collapse" role="navigation">
                            <ul class="nav navbar-nav">
                            </ul>
						</nav>
					</div>
					<div class="col-sm-6 col-sm-offset-3">
	                    <div class="padding">
	                        <div class="full col-sm-9">
	                            <div class="panel panel-default">
									@include('partials.errors')
	                                @yield('content')
	                            </div>
	                        </div>
	                    </div>
                    </div>
				</div>
			</div>
		</div>
	</div>



	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>