app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['as' => 'auth.'], function(){
    // Authentication routes...
    Route::get('connexion', 'Auth\AuthController@getLogin')->name('login');
    Route::post('connexion', 'Auth\AuthController@postLogin')->name('login');
    Route::get('deconnexion', 'Auth\AuthController@getLogout')->name('logout');

    // Registration routes...
    Route::get('inscription', 'Auth\AuthController@getRegister')->name('register');
    Route::post('inscription', 'Auth\AuthController@postRegister')->name('register');
});


// Routes inaccessibles si l'utilisateur n'est pas authentifié
Route::group(['middleware' => 'auth'], function(){
            Route::get('/', 'PageController@newsFeed')->name('news-feed');
            Route::get('/annuaire', 'UserController@index')->name('directory');
            Route::resource('users', 'UserController');
            Route::post('/users/{users}/friends', 'UserController@storeFriend')->name('users.friends.store');
            Route::resource('messages', 'MessageController', ['only' => ['store', 'destroy']]);
            Route::post('messages/{messages}/like', 'MessageController@like')->name('messages.likes.store');
            Route::resource('messages.comments', 'CommentController', ['only' => ['store', 'destroy']]);
            Route::post('messages/{messages}/comments/{comments}/like', 'CommentController@like')->name('messages.comments.likes.store');
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
	public function likes(){
		return $this->morphMany(\App\Like::class, 'likable');
	}

	public function user(){
		return $this->belongsTo(User::class);
	}

	public function message(){
		return $this->belongsTo(Message::class);
	}
	
	protected $fillable = ['message_id', 'user_id', 'content'];
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Message;
use App\Comment;

class CommentController extends Controller
{	

	/**
	* Store a newly created resource in storage.
	*
	* @param  \Illuminate\Http\Request  $request
	* @return \Illuminate\Http\Response
	*/
	public function store(Request $request, $message_id)
	{

		$message = Message::findOrFail($message_id);

		$message->comments()->create([
			'user_id' => auth()->user()->id,
			'message_id' => $message_id,
			'content' => $request->get('content'),
		]);

		return redirect()->back();
	}

	/**
	* Remove the specified resource from storage.
	*
	* @param  int  $id
	* @return \Illuminate\Http\Response
	*/
	public function destroy($comment_id)
	{
		$comment = Comment::findOrFail($comment_id); 
		$comment->destroy();
		
		return redirect()->back();
	}

	/**
	* Remove the specified resource from storage.
	*
	* @param  int  $id
	* @return \Illuminate\Http\Response
	*/
	public function like(Request $request, $message_id, $comment_id)
	{
		$comment = Comment::findOrFail($comment_id);

		$comment->likes()->create([
			'user_id' => auth()->user()->id,
		]);

		return redirect()->back();
	}
}

resources/views/comment/form.blade.php
<form class="padding" method="post" action="{{route('messages.comments.store', ['messages' => $message->id])}}">
    {{ csrf_field() }}
    <div class="input-group">
        <div class="input-group-btn">
            <button class="btn btn-primary">Commenter</button>
        </div>
        <input name="content" class="form-control" placeholder="Ajouter un commentaire" type="text">
    </div>
</form>

resources/views/comment/single.blade.php
<div class="commentaire">
	<div class="fb-blue">{{$comment->user->name}}: </div>{{$comment->content}}
	</div>
	<form method="post" action="{{route('messages.comments.likes.store', ['comment' => $comment, 'messages' => $message])}}">
		{{ csrf_field() }}
		{{-- si les likes sont > 0 alors on affiche le nombre de kiff(s) --}}
		@if(count($comment->likes))
			{{count($comment->likes)}}
		@endif
		<button type="submit" class="btn btn-default">Je kiff <i class="glyphicon glyphicon-thumbs-up"></i></button>
	</form>