app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['as' => 'auth.'], function(){
    // Authentication routes...
    Route::get('connexion', 'Auth\AuthController@getLogin')->name('login');
    Route::post('connexion', 'Auth\AuthController@postLogin')->name('login');
    Route::get('deconnexion', 'Auth\AuthController@getLogout')->name('logout');

    // Registration routes...
    Route::get('inscription', 'Auth\AuthController@getRegister')->name('register');
    Route::post('inscription', 'Auth\AuthController@postRegister')->name('register');
});


// Routes inaccessibles si l'utilisateur n'est pas authentifié
Route::group(['middleware' => 'auth'], function(){
            Route::get('/', 'PageController@newsFeed')->name('news-feed');
            Route::get('/annuaire', 'UserController@index')->name('directory');
            Route::resource('users', 'UserController');
            Route::post('/users/{users}/friends', 'UserController@storeFriend')->name('users.friends.store');
            Route::resource('messages', 'MessageController', ['only' => ['store', 'destroy']]);
            Route::post('messages/{messages}/like', 'MessageController@like')->name('messages.likes.store');
            Route::resource('messages.comments', 'CommentController', ['only' => ['store', 'destroy']]);
            Route::post('messages/{messages}/comments/{comments}/like', 'CommentController@like')->name('messages.comments.likes.store');
});

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use App\User;
use App\Comment;
use App\Message;
use App\Like;

/**
 * App\User
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $remember_token
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 */
class User extends Model implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract{
	use Authenticatable, Authorizable, CanResetPassword;

	public function comments(){
		return $this->hasMany(Comment::class);
	}

	public function messages(){
		return $this->hasMany(Message::class);
	}

	public function likes(){
		return $this->hasMany(Like::class);
	}

	public function friends(){
		return $this->belongsToMany(User::class, 'user_user', 'user_id', 'friend_id')->withTimestamps();
	}

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password', 'age'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = User::all()->except(auth()->user()->id);
        return view('pages.users.directory',  compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $utilisateurCourant = User::findOrFail($id);
        $messages = $utilisateurCourant->messages()->orderBy('id', 'desc')->get();
        return view('pages.users.profile', compact('utilisateurCourant', 'messages'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $utilisateurCourant = User::findOrFail($id);
        return view('pages.users.edit', compact('utilisateurCourant'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

      /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeFriend(Request $request, $user_id)
    {
        $friend = User::findOrFail($user_id); 
        auth()->user()->friends()->attach($friend); 
        return redirect()->back();
    }
}

resources/views/pages/users/directory.blade.php
@extends('layout.facebook')


@section('content')

	<div class="panel panel-default">
		<div class="panel-heading">Ajouter des amis</div>
		<div class="panel-body">
		@foreach($users as $user)
			@include('user.friend', [ 'user' => $user ])
		@endforeach
		{{-- parcourir la liste des utilisateurs avec @foreach --}}
		{{-- dans la boucle inclure la vue friend pour chaque utilisateur sauf pour l'utilisateur courant --}}
		</div>
	</div>

@endsection

resources/views/pages/users/edit.blade.php
@extends('layout.facebook')

@section('content')

<div class="panel panel-default">
	<div class="panel panel-heading">
		Modifier le profil
	</div>

	<form class="form" method="post" action="{{route('auth.register')}}">
	    {!! csrf_field() !!}

	    <div class="input-group text-center col-sm-12 padding">
	        <input class="form-control input-lg" type="text" name="name" placeholder="Nom"  value="{{ old('name') }}">
	    </div>

	    <div class="input-group text-center col-sm-12 padding">
	        <input class="form-control input-lg" type="email" name="email" placeholder="Email"  value="{{ old('email') }}">
	    </div>

	    <div class="input-group text-center col-sm-12 padding">
	        <input class="form-control input-lg" type="password" placeholder="Mot de passe" name="password">
	    </div>

	    <div class="input-group text-center col-sm-12 padding">
	        <input class="form-control input-lg" type="password" placeholder="Confirmer le mot de passe" name="password_confirmation">
	    </div>

	    <div class="input-group text-center col-sm-12 padding">
	        <button class="btn btn-lg btn-primary" type="submit">Modifier</button>
	    </div>
	</form>

	</div>
@endsection

resources/views/pages/users/profile.blade.php
@extends('layout.facebook')

@section('content')
    <h2>{{$utilisateurCourant->name}}</h2>
    {{-- inclure la vue single de l'utilisateur $user --}}
    @include('user.single', [ 'utilisateurCourant' => $utilisateurCourant, 'messages' => $messages])
@endsection