app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['as' => 'auth.'], function(){
    // Authentication routes...
    Route::get('connexion', 'Auth\AuthController@getLogin')->name('login');
    Route::post('connexion', 'Auth\AuthController@postLogin')->name('login');
    Route::get('deconnexion', 'Auth\AuthController@getLogout')->name('logout');

    // Registration routes...
    Route::get('inscription', 'Auth\AuthController@getRegister')->name('register');
    Route::post('inscription', 'Auth\AuthController@postRegister')->name('register');
});


// Routes inaccessibles si l'utilisateur n'est pas authentifié
Route::group(['middleware' => 'auth'], function(){
            Route::get('/', 'PageController@newsFeed')->name('news-feed');
            Route::get('/annuaire', 'UserController@index')->name('directory');
            Route::resource('users', 'UserController');
            Route::post('/users/{users}/friends', 'UserController@storeFriend')->name('users.friends.store');
            Route::resource('messages', 'MessageController', ['only' => ['store', 'destroy']]);
            Route::post('messages/{messages}/like', 'MessageController@like')->name('messages.likes.store');
            Route::resource('messages.comments', 'CommentController', ['only' => ['store', 'destroy']]);
            Route::post('messages/{messages}/comments/{comments}/like', 'CommentController@like')->name('messages.comments.likes.store');
});

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
	public function likes(){
		return $this->morphMany(\App\Like::class, 'likable');
	}

	public function comments(){
		return $this->hasMany(Comment::class);
	}

	public function user(){
		return $this->belongsTo(User::class);
	}

	public function scopeReadableFor($query, $user){
		$friends = $user->friends->pluck('id')->toArray();
		array_push($friends, $user->id);
		return $query->whereIn('user_id', $friends)->orderBy('created_at', 'desc');
	}

	protected $fillable = ['user_id', 'content'];
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Message;

class MessageController extends Controller
{
	/**
	* Store a newly created resource in storage.
	*
	* @param  \Illuminate\Http\Request  $request
	* @return \Illuminate\Http\Response
	*/
	public function store(Request $request)
	{
		$message = Message::create([
			'user_id' => auth()->user()->id,
			'content' => $request->get('content'),
		]);

		return redirect()->back();
	}

	/**
	* Remove the specified resource from storage.
	*
	* @param  int  $id
	* @return \Illuminate\Http\Response
	*/
	public function destroy($message_id)
	{
		$message = Message::findOrFail($message_id); 
		$message->destroy();

		return redirect()->back();
	}

	/**
	* Remove the specified resource from storage.
	*
	* @param  int  $id
	* @return \Illuminate\Http\Response
	*/
	public function like(Request $request, $message_id)
	{
		$message = Message::findOrFail($message_id);

		$message->likes()->create([
			'user_id' => auth()->user()->id,
		]);

		return redirect()->back();
	}
}

resources/views/message/form.blade.php
<div class="well">
	<form class="form-horizontal" role="form" method="POST" action="{{route('messages.store')}}">
		<h4>What's New</h4>
		{{ csrf_field() }}
		<div class="form-group" style="padding:14px;">
			<textarea name="content" class="form-control" placeholder="Ecrire un message"></textarea>
		</div>
		<button class="btn btn-primary pull-right" type="submit">Poster</button>
        <ul class="list-inline">
            <li><a href=""><i class="glyphicon glyphicon-upload"></i></a></li>
            <li><a href=""><i class="glyphicon glyphicon-file"></i></a></li>
            <li><a href=""><i class="glyphicon glyphicon-map-marker"></i></a></li>
        </ul>
	</form>
</div>

resources/views/message/single.blade.php
	<div class="panel panel-default">
		<div class="panel-heading">{{$message->user->name}} - {{$message->created_at->diffForHumans()}}</div>
		<div class="panel-body">

			<div class="message">
				{{-- contenu du message --}}
				{{$message->content}}
            </div>
            <form method="post" action="{{route('messages.likes.store', ['messages' => $message])}}">
                {{ csrf_field() }}
				{{-- si les likes sont > 0 alors on affiche le nombre de kiff(s) --}}
				@if(count($message->likes))
					{{count($message->likes)}}
				@endif
                <button type="submit" class="btn btn-default right">Je kiff <i class="glyphicon glyphicon-thumbs-up"></i></button>
            </form>


            @foreach($message->comments as $comment)
			<div class="padding commentaires">
				{{-- inclure la vue single du commentaire $comment --}}
				@include('comment.single', [ 'comment' => $comment, 'message' => $message])
			</div>
            @endforeach
			{{-- inclure la vue form du message $message --}}
			@include('comment.form', [ 'message' => $message])
		</div>
	</div>